window.ISESE_DATA = {
  media: {
    oponIfa: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Opon%20Ifa%20%28Ifa%20Tray%29.jpg",
    osunShrine: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Osun-Osogbo%20Sacred%20shrine%2001.jpg",
    gelede: "https://commons.wikimedia.org/wiki/Special:Redirect/file/WLA%20ima%20Yoruba%20cap%20mask%20for%20Gelende%20masquerade.jpg",
    osunStatue: "https://commons.wikimedia.org/wiki/Special:Redirect/file/A%20statue%20at%20Osun%20Osogbo%20Grove.jpg"
  },
  orisas: [
    {
      slug:"orunmila", name:"Òrúnmìlà", classification:"Òrìṣà of Ifá and divinatory wisdom",
      domains:["Ifá","wisdom","divination","destiny"],
      lead:"Òrúnmìlà stands at the center of Ifá as the sacred intelligence through which questions of character, destiny, ethics and choice are interpreted.",
      image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Opon%20Ifa%20%28Ifa%20Tray%29.jpg",
      overview:[
        "Within Yoruba religious thought, Òrúnmìlà is closely associated with Ifá, the divinatory and philosophical corpus preserved through trained specialists. His importance is not simply that of foretelling events. Ifá is used to think through conduct, obligations, relationships, sacrifice, timing and the consequences of choices.",
        "Many Yoruba communities understand Òrúnmìlà as a witness to destiny and as a source of counsel. The precise theology, titles and ritual emphases vary among lineages, towns and diasporic traditions, so no single local explanation should be treated as universal."
      ],
      titles:"Common references include Òrúnmìlà and Ifá, while praise names and lineage titles vary. In practice, the distinction between the Òrìṣà and the divinatory institution around Ifá may be expressed differently by different teachers.",
      oral:"Ifá knowledge is carried through Odù, verses, narratives, proverbs, prayers, ritual language and interpretive training. Oral transmission is central: memorization is important, but interpretation also depends on apprenticeship, context and the ability to relate a verse responsibly to the matter being examined.",
      material:"Material culture associated with Ifá includes ọ̀pọ́n Ifá (divination trays), ìrọ̀kẹ̀ Ifá, ikin, ọ̀pẹ̀lẹ̀, carved containers and other objects whose form and decoration can vary widely. Their visual language often combines geometry, figuration and the face of Èṣù or other motifs relevant to communication and divination.",
      worship:"Babaláwo and other Ifá specialists undergo long periods of training. Consultation is therefore not merely the act of casting; it belongs to a wider institution of study, ritual discipline, ethics and community responsibility.",
      geography:"Strong Ifá traditions are documented across Yoruba-speaking regions, including Ilé-Ifẹ̀, Ọ̀yọ́, Ekiti, Ondo, Ìjẹ̀bú and other areas, with distinctive local schools and vocabularies.",
      festivals:"Public observances connected with Ifá differ by town and lineage. Some communities maintain annual festivals, temple observances or lineage gatherings, while other practices are more private.",
      variation:"Ifá is especially sensitive to variation because oral corpora, recitation style, naming, ritual procedure and interpretive conventions may differ significantly between lineages.",
      diaspora:"Ifá traveled through Atlantic histories and is now practiced in several diasporic traditions. Yoruba-derived systems in Cuba, Brazil, the United States and elsewhere developed their own institutions while maintaining important continuities with West African Ifá.",
      misconceptions:"Reducing Ifá to fortune-telling misses its philosophical, ethical and literary dimensions. It is better understood as a broad system of consultation, knowledge transmission, ritual practice and reflection on human choice.",
      refs:["UNESCO — Ifá Divination System","Metropolitan Museum of Art — Yoruba divination arts","Wikimedia Commons — Opon Ifa documentation"]
    },
    {
      slug:"esu", name:"Èṣù", classification:"Òrìṣà of mediation, consequence and the crossroads",
      domains:["communication","crossroads","exchange","accountability"],
      lead:"Èṣù occupies a central position in Yoruba thought as a force of mediation, consequence, communication and the movement between different realms of obligation.",
      image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Osun%20Osogbo%20Sacred%20Groove%20-%20The%20Esu%20shrine.jpg",
      overview:[
        "Èṣù is one of the most complex figures in Yoruba religion. He is associated with crossroads, exchange, message-bearing, testing, reciprocity and the consequences that follow speech and action.",
        "Missionary-era translations often collapsed Èṣù into the Christian devil, a comparison that has distorted public understanding. Yoruba traditions present a far more complex figure whose roles are embedded in ritual order, communication and moral consequence."
      ],
      titles:"Names and praise titles vary across regions and lineages. Some titles emphasize movement, cleverness, mediation or presence at points of exchange.",
      oral:"Stories concerning Èṣù often turn on language, ambiguity, contracts, promises, arrogance and the consequences of ignoring obligations. Their point is frequently ethical rather than simply mischievous.",
      material:"Representations include shrine forms, staffs, stones, carved figures and other localized objects. There is no single universal iconography for all Yoruba communities.",
      worship:"Èṣù is invoked in many ritual contexts because communication and exchange are fundamental to relationships among persons, ancestors and Òrìṣà. Practice differs by lineage and ritual setting.",
      geography:"Èṣù traditions are widespread across Yoruba regions and have also become highly visible in diasporic religions.",
      festivals:"Public observances differ by locality. Some shrines are embedded in larger festival complexes, while other forms of devotion remain household- or lineage-centered.",
      variation:"Regional theology may emphasize messenger roles, crossroads, justice, unpredictability or the testing of character in different proportions.",
      diaspora:"Èṣù appears under related names in several Atlantic traditions, where local histories shaped pronunciation, ritual forms and theology.",
      misconceptions:"Èṣù should not be equated automatically with 'the devil.' That equation emerged through translation histories that did not reflect the complexity of Yoruba categories.",
      refs:["Yoruba religious studies on Èṣù","Osun-Osogbo Sacred Grove documentation","Museum collections of Yoruba shrine arts"]
    },
    {
      slug:"ogun", name:"Ògún", classification:"Òrìṣà of iron, technology, labor and the road",
      domains:["iron","craft","work","roads"],
      lead:"Ògún is associated with iron, technological transformation, disciplined labor, dangerous tools, roads and the responsibilities that accompany power.",
      image:null,
      overview:[
        "Across many Yoruba communities, Ògún is closely linked to iron and the human capacity to transform the environment through tools. Hunters, blacksmiths, drivers, mechanics and other professions may invoke Ògún in ways shaped by their work.",
        "His symbolism joins productivity and danger: the same iron that builds also cuts. This makes responsibility, restraint and disciplined use of power important themes in narratives about Ògún."
      ],
      titles:"Praise names frequently emphasize iron, forests, roads, labor and fearsome strength. Exact forms vary widely by locality.",
      oral:"Ògún narratives often describe clearing paths, opening difficult spaces, forging technology and the costs of uncontrolled force. They can be read as reflections on work, courage and responsibility.",
      material:"Iron implements, tools, chains, blades, anvils and forged forms can become part of Ògún shrine environments. The specific arrangement is not universal.",
      worship:"Devotion is frequently connected to occupations that rely on iron or dangerous technology. Ritual specialists, families and occupational groups may maintain different practices.",
      geography:"Ògún traditions are found across Yoruba regions and have strong diasporic continuities.",
      festivals:"Several towns hold public festivals for Ògún, while occupational associations may maintain their own observances.",
      variation:"Local traditions may emphasize hunting, blacksmithing, road travel, warfare, agriculture or modern technology.",
      diaspora:"Ògún became especially important in Atlantic religions, often remaining strongly associated with iron, labor and technological force.",
      misconceptions:"Ògún is not simply a 'war god.' Iron, labor, craft, movement and technological responsibility are equally central to many understandings.",
      refs:["Yoruba studies on Ògún and technology","Museum collections of iron shrine arts","Regional festival documentation"]
    },
    {
      slug:"osun", name:"Ọ̀ṣun", classification:"Òrìṣà associated with the Ọ̀ṣun River, beauty and fertility",
      domains:["river","fertility","beauty","diplomacy"],
      lead:"Ọ̀ṣun is strongly associated with fresh water, fertility, beauty, diplomacy, prosperity and the sacred landscape of the Ọ̀ṣun River.",
      image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Osun-Osogbo%20Sacred%20shrine%2001.jpg",
      overview:[
        "Ọ̀ṣun is among the most widely recognized Yoruba Òrìṣà. In Ọ̀ṣogbo, the river and sacred grove form a major ritual landscape in which shrines, sculpture, forest and water are integrated.",
        "Her traditions also extend far beyond Ọ̀ṣogbo. Different towns, lineages and diasporic communities preserve distinct praise names, ritual emphases and understandings of her character."
      ],
      titles:"Titles often evoke the river, wealth, beauty, motherhood, diplomacy and sweetness, but praise poetry differs by community.",
      oral:"Narratives of Ọ̀ṣun frequently foreground intelligence, negotiation, fertility, social recognition and the consequences of excluding female power from collective affairs.",
      material:"River vessels, cloth, beads, brass objects, fans, sculptural forms and local shrine arts may appear in Ọ̀ṣun contexts, but iconography varies.",
      worship:"Priesthood and devotion can center on rivers, shrines, households and community festivals. Water is not merely decorative symbolism; it is part of the sacred geography itself.",
      geography:"Ọ̀ṣogbo is globally known because of the Sacred Grove, but Ọ̀ṣun traditions are distributed widely across Yoruba-speaking regions.",
      festivals:"The annual Ọ̀ṣun-Ọ̀ṣogbo festival is one of the most visible Yoruba religious festivals internationally, drawing devotees and visitors to the sacred grove and river.",
      variation:"Local traditions may differ in color associations, ritual objects, praise names and relationships with other Òrìṣà.",
      diaspora:"Ọ̀ṣun/Ọ̀ṣum traditions became influential across Cuba, Brazil and other parts of the Atlantic world, where local ritual systems developed distinctive forms.",
      misconceptions:"Popular culture often reduces Ọ̀ṣun to beauty or romance. Yoruba traditions also emphasize authority, fertility, diplomacy, wealth, sacred water and social intelligence.",
      refs:["UNESCO — Osun-Osogbo Sacred Grove","Wikimedia Commons — Osun-Osogbo Sacred Grove","Studies of Ọ̀ṣun worship and female authority"]
    },
    {
      slug:"sango", name:"Ṣàngó", classification:"Òrìṣà of thunder, kingship and forceful authority",
      domains:["thunder","kingship","authority","performance"],
      lead:"Ṣàngó joins thunder, royal authority, public performance, charisma and the disciplined use of force.",
      image:null,
      overview:[
        "Ṣàngó is deeply connected with the political and ritual history of Ọ̀yọ́. Traditions linking him with kingship, thunder and public authority have produced a rich body of praise poetry, dance, drumming and sculptural art.",
        "His public image can be dramatic, but the tradition also speaks to legitimacy, justice, leadership and the dangers of excessive power."
      ],
      titles:"Praise names often refer to thunder, fire, royal presence and the intensity of public authority.",
      oral:"Ṣàngó narratives connect royal history, charisma, anger, justice and the responsibilities of command. Oríkì and performance are especially important to his public memory.",
      material:"The double-axe motif, known widely through oṣé Ṣàngó forms, is prominent in museum collections and performance contexts. Beadwork and dance objects may also be important.",
      worship:"Devotion may involve shrine communities, priesthoods, drumming and possession performance, with details differing by town and lineage.",
      geography:"Ọ̀yọ́ is central to many historical traditions of Ṣàngó, though worship is widespread across Yoruba areas.",
      festivals:"Ṣàngó festivals and public performances remain important in several communities and have also become internationally recognized through diasporic traditions.",
      variation:"Historical and ritual narratives can differ substantially across Ọ̀yọ́, other Yoruba regions and the diaspora.",
      diaspora:"Ṣàngó became one of the most visible Yoruba-derived Òrìṣà in Atlantic religions, particularly in Cuba, Brazil and Trinidad.",
      misconceptions:"Ṣàngó is not adequately described as only a thunder god. His traditions also engage kingship, justice, charisma, performance and political memory.",
      refs:["Studies of Ọ̀yọ́ kingship and Ṣàngó","Museum collections of oṣé Ṣàngó","Diaspora studies of Ṣàngó traditions"]
    },
    {
      slug:"obatala", name:"Ọbàtálá", classification:"Òrìṣà associated with creation, clarity and seniority",
      domains:["creation","clarity","seniority","ethical restraint"],
      lead:"Ọbàtálá is widely associated with creation, seniority, composure, white cloth and ideals of clarity and ethical restraint.",
      image:null,
      overview:[
        "Across Yoruba communities, Ọbàtálá occupies an important place in narratives of creation and seniority. White clothing and calmness are prominent associations in many traditions.",
        "Theological details differ by community, including relationships among Ọbàtálá, Òrìṣàńlá and other senior creative powers."
      ],
      titles:"Names and titles may emphasize seniority, whiteness, creation and composure. Local equivalences should not be assumed without context.",
      oral:"Stories concerning Ọbàtálá often address creation, human difference, error, responsibility, patience and correction.",
      material:"White cloth, beads, staffs, vessels and shrine architecture may be significant, but local practice determines meaning.",
      worship:"Devotional practice often emphasizes composure, ritual cleanliness and seniority. Specific prohibitions and offerings vary by lineage.",
      geography:"Ọbàtálá traditions are widespread and particularly important in Ilé-Ifẹ̀ and other Yoruba centers.",
      festivals:"Festivals and temple observances vary by town and may be linked with local histories of creation and kingship.",
      variation:"The names Ọbàtálá and Òrìṣàńlá are related in many traditions but should not be flattened into a single uniform theology.",
      diaspora:"Ọbàtálá traditions became highly influential in several Atlantic religions.",
      misconceptions:"Popular descriptions sometimes make Ọbàtálá a simple abstract 'creator god.' Yoruba traditions are richer, localized and embedded in ritual communities.",
      refs:["Studies of Yoruba creation traditions","Ilé-Ifẹ̀ religious history","Diaspora studies of Ọbàtálá"]
    },
    {
      slug:"yemoja", name:"Yemọja", classification:"Òrìṣà associated with waters, motherhood and protection",
      domains:["waters","motherhood","protection","continuity"],
      lead:"Yemọja is associated with water, motherhood, care, protection and continuity, with major differences between West African and diasporic expressions.",
      image:null,
      overview:[
        "In Yoruba contexts, Yemọja traditions are historically connected with inland waters and specific regional communities. Diasporic developments expanded and transformed some of these associations.",
        "Because Yemọja has become globally popular, it is especially important to distinguish documented Yoruba traditions from later universalized imagery."
      ],
      titles:"Praise names vary by region and may emphasize motherhood, water, protection and senior female authority.",
      oral:"Narratives frequently foreground motherhood, care, community, emotional force and the responsibilities of nurture.",
      material:"Water vessels, cloth, beads and localized shrine forms may appear in Yemọja devotion. Blue-and-white imagery is especially prominent in some diasporic contexts but should not be treated as universal.",
      worship:"Devotion takes different forms in West Africa and the diaspora, with local water bodies and lineage histories shaping practice.",
      geography:"Historical Yoruba centers of Yemọja devotion include inland communities as well as later broader regional traditions.",
      festivals:"Public festivals occur in several communities, including contemporary celebrations that have grown in visibility.",
      variation:"This is an area where regional and diasporic variation is particularly significant.",
      diaspora:"Yemọja became a major Atlantic Òrìṣà and acquired strong oceanic associations in several diasporic traditions.",
      misconceptions:"Treating every modern ocean image as ancient and universal Yoruba iconography obscures important historical change.",
      refs:["Studies of Yemọja in Yoruba and Atlantic traditions","Regional festival documentation","Museum and ethnographic collections"]
    },
    {
      slug:"oya", name:"Ọya", classification:"Òrìṣà associated with winds, transformation and the Niger River",
      domains:["wind","transformation","river","market"],
      lead:"Ọya is associated with powerful wind, transformation, movement, markets and important river traditions.",
      image:null,
      overview:[
        "Ọya traditions often emphasize forceful movement, change and the capacity to transform circumstances. She is also associated with specific river geographies and with public spaces of exchange.",
        "Her meanings differ across Yoruba regions and diasporic systems, where storm imagery sometimes becomes especially prominent."
      ],
      titles:"Praise names can emphasize wind, rapid movement, courage, markets and riverine power.",
      oral:"Ọya narratives frequently explore transformation, independence, courage and the social force of women in public life.",
      material:"Cloth, beads, market symbolism, river associations and localized shrine objects may appear, but there is no single universal visual code.",
      worship:"Priesthood and household devotion vary by region, with local histories shaping ritual emphasis.",
      geography:"Ọya traditions are associated with parts of the Niger River region and with Yoruba communities in multiple areas.",
      festivals:"Observances differ significantly by locality.",
      variation:"Diasporic storm imagery should not erase older regional associations with river, market and transformation.",
      diaspora:"Ọya became highly visible in Atlantic religions, especially in Cuba and Brazil.",
      misconceptions:"Reducing Ọya to a generic storm goddess overlooks river, market, social and historical dimensions.",
      refs:["Regional studies of Ọya","Diaspora studies of Oya/Iansã","Yoruba gender and market history"]
    },
    {
      slug:"osanyin", name:"Ọ̀sányìn", classification:"Òrìṣà associated with leaves and specialist herbal knowledge",
      domains:["leaves","herbal knowledge","specialist practice","forest"],
      lead:"Ọ̀sányìn is closely associated with ewé—leaves—and with the disciplined specialist knowledge through which plants are identified, combined and understood.",
      image:null,
      overview:[
        "Yoruba traditions surrounding Ọ̀sányìn emphasize the importance of leaves to ritual and healing knowledge. This does not mean that every plant use is interchangeable or universally known.",
        "Expertise is commonly lineage-based and practical. Identification, harvesting, preparation, timing, language and context all matter."
      ],
      titles:"Praise names frequently emphasize leaves, forest knowledge, secrecy and specialist expertise.",
      oral:"Songs, formulas, plant names, proverbs and apprenticeship are important vehicles of transmission.",
      material:"Museum collections include distinctive staffs associated with Ọ̀sányìn, often composed of iron figures and birds. Their forms should be understood as documented ritual art rather than generic logos.",
      worship:"Specialists may maintain relationships with Ọ̀sányìn within broader systems of herbal and ritual knowledge.",
      geography:"Plant knowledge varies strongly by ecology and locality, making regional context especially important.",
      festivals:"Public festivals are less globally standardized than those of some other Òrìṣà; practice may be specialist- or lineage-centered.",
      variation:"Local plant taxonomies, ritual language and materials differ, so specific formulas should never be generalized casually.",
      diaspora:"Ọ̀sányìn/Osain became important in Atlantic ritual systems, particularly where plant knowledge remained central.",
      misconceptions:"It is misleading to treat Ọ̀sányìn as a decorative 'herb god.' The tradition points toward disciplined expertise, ecology and transmission.",
      refs:["Yoruba ethnobotanical studies","Museum collections of Ọ̀sányìn staffs","Studies of plant knowledge in Atlantic religions"]
    },
    {
      slug:"olokun", name:"Olókun", classification:"Sacred power associated with deep waters, wealth and mystery",
      domains:["deep water","wealth","mystery","depth"],
      lead:"Olókun is associated with deep water, wealth, hidden abundance and forms of power that are difficult to reduce to a single image.",
      image:null,
      overview:[
        "Olókun traditions differ significantly across Yoruba and neighboring cultural histories. In some Yoruba contexts Olókun is strongly linked with depth, wealth and the sea; other regions preserve distinct gendered and theological understandings.",
        "Because the name also has important histories in Edo traditions, careful attention to cultural context is essential."
      ],
      titles:"Praise names and gendered language vary, reflecting important regional differences.",
      oral:"Narratives often emphasize depth, inaccessible wealth, mystery and the limits of human control.",
      material:"Water vessels, beads and localized shrine objects may be used, but no single iconography should be universalized.",
      worship:"Practice varies by region and may be connected with coastal or water-oriented communities.",
      geography:"Coastal Yoruba areas and diasporic contexts have developed especially visible Olókun traditions.",
      festivals:"Public observances depend on locality.",
      variation:"Regional variation is central and should be stated explicitly whenever Olókun is discussed.",
      diaspora:"Olókun became highly influential in several Atlantic religions, with new ritual and theological developments.",
      misconceptions:"Modern internet imagery often blends Yoruba and Edo traditions without distinction; responsible documentation keeps those histories separate.",
      refs:["Studies of Olókun across Yoruba and Edo contexts","Atlantic religious history","Coastal shrine documentation"]
    },
    {
      slug:"orisa-oko", name:"Òrìṣà Oko", classification:"Òrìṣà associated with farming, land and agricultural order",
      domains:["agriculture","land","farming","community"],
      lead:"Òrìṣà Oko is associated with agriculture, cultivated land, food production and the social order sustained by farming.",
      image:null,
      overview:[
        "Agriculture has long been central to Yoruba social life, and Òrìṣà Oko traditions connect cultivation with ritual responsibility, land and communal wellbeing.",
        "Historical objects associated with Òrìṣà Oko in museum collections show how agricultural identity can be expressed through highly refined ritual art."
      ],
      titles:"Praise names and local titles often refer to farming, land, food and rural prosperity.",
      oral:"Narratives may emphasize cultivation, social responsibility, justice and the value of productive labor.",
      material:"Documented objects include staffs, sheaths and other forms connected with agricultural ritual traditions.",
      worship:"Practice may be associated with farming communities, households and local specialists.",
      geography:"Òrìṣà Oko traditions are distributed across multiple Yoruba regions with different agricultural histories.",
      festivals:"Observances may follow local agricultural cycles and community calendars.",
      variation:"The importance of specific crops, objects and ritual roles varies locally.",
      diaspora:"Òrìṣà Oko is less globally visible than several other Òrìṣà but remains part of broader diasporic pantheons.",
      misconceptions:"Treating agriculture as merely economic misses its ritual, social and ecological significance.",
      refs:["Museum collections of Òrìṣà Oko objects","Yoruba agricultural history","Regional ritual studies"]
    },
    {
      slug:"ibeji", name:"Ìbejì", classification:"Sacred twin tradition associated with family, continuity and remembrance",
      domains:["twins","family","continuity","remembrance"],
      lead:"Ìbejì traditions center on twins, family continuity and the special social and spiritual attention historically given to multiple birth among Yoruba communities.",
      image:null,
      overview:[
        "Yoruba societies are well known for a historically high cultural visibility of twin births. Ìbejì traditions developed rich forms of family practice, praise language and artistic representation.",
        "Museum collections contain many carved ere Ìbejì figures. These should be understood in the context of family remembrance and care, not as generic dolls or decorative sculptures."
      ],
      titles:"Twin praise names and family terminology are central to the tradition and vary in performance and local practice.",
      oral:"Songs, praise names and family narratives play major roles in sustaining the social identity of twins.",
      material:"Ere Ìbejì figures are among the most widely collected Yoruba artworks internationally, though their museum history must be distinguished from living family practice.",
      worship:"Practices historically centered on family relationships, remembrance and care, with considerable local variation.",
      geography:"Twin traditions are widespread across Yoruba communities.",
      festivals:"Some communities hold public twin festivals or contemporary cultural celebrations.",
      variation:"Family practice, sculpture style and ritual emphasis vary by region and period.",
      diaspora:"The cultural significance of twins traveled into Atlantic Yoruba-derived traditions in different forms.",
      misconceptions:"Ere Ìbejì should not be treated simply as collectible art objects detached from the family histories that gave them meaning.",
      refs:["Museum collections of ere Ìbejì","Yoruba family and twin studies","Contemporary twin festival documentation"]
    }
  ],
  oogun: [
    {name:"ISEGUN AROKA",cat:"Victory",summary:"A named Yoruba working associated in practitioner archives with overcoming hostility, opposition and destructive talk."},
    {name:"ARISOYIN",cat:"Social / Favour",summary:"A traditional name associated with being spoken of favourably while absent."},
    {name:"IMU IRINAJO DARA",cat:"Travel",summary:"A named preparation associated with safe travel and a journey going well."},
    {name:"ISAN GBESE",cat:"Prosperity",summary:"An archive title connected with debt, repayment and relief from financial burden."},
    {name:"OOGUN KOSOFO",cat:"Protection",summary:"A practitioner-listed preparation associated with preventing loss."},
    {name:"IKUJENJO",cat:"Protection",summary:"A protective archive title traditionally associated with warding off untimely death."},
    {name:"AABO LOWO EPE",cat:"Protection",summary:"A named protection working associated with shielding a person from curses or hostile speech."},
    {name:"ISORI MOTOR",cat:"Travel",summary:"A traditional road and vehicle protection title found in practitioner collections."},
    {name:"IMU OJO DURO",cat:"Weather / Agriculture",summary:"A traditional rain-stopping title documented in practitioner material."},
    {name:"ONFA OWO",cat:"Prosperity",summary:"A named money-attraction preparation in Yoruba practitioner archives."},
    {name:"OGUN ANU",cat:"Social / Favour",summary:"A preparation name associated with mercy, favourable reception and softening difficult social encounters."},
    {name:"IWEJU",cat:"Social / Favour",summary:"A practitioner title associated with favourable regard and social reception."},
    {name:"ISORE",cat:"Prosperity",summary:"A scarce practitioner-listed title connected with blessing, gift or favourable outcome depending on source."},
    {name:"TURARI",cat:"Plants & Preparations",summary:"A broad fumigation or aromatic preparation category appearing in traditional practitioner material."},
    {name:"IFURA",cat:"Protection",summary:"A named preparation associated with alertness, caution and avoiding hidden danger."},
    {name:"AFERI",cat:"Social / Favour",summary:"A practitioner title connected with attraction, visibility or being sought after."},
    {name:"ERO IGBONA",cat:"Ìwòsàn",summary:"A traditional archive name connected with states of heat or bodily discomfort; interpretations vary by source."},
    {name:"IMO ODE",cat:"Travel",summary:"A title associated with hunting, movement through difficult terrain and safe return."}
  ],
  dictionary: [
    {term:"Àṣẹ",meaning:"Authority, efficacy, power to make things happen.",context:"A foundational Yoruba concept used in religious, social and performative contexts.",related:["Iwúre","Òrìṣà"]},
    {term:"Àṣà",meaning:"Culture, custom, inherited way of doing things.",context:"Used for the practices, values and social forms through which a community expresses itself.",related:["Ìṣẹ̀ṣe","Èdè"]},
    {term:"Àjẹ́",meaning:"A complex concept of female spiritual power.",context:"Meaning depends strongly on context; it should not automatically be translated as 'witchcraft'.",related:["Àwọn Ìyá","Gèlèdé"]},
    {term:"Àwọn Ìyá",meaning:"The Mothers.",context:"A respectful expression used in discussions of senior female spiritual power and social authority.",related:["Àjẹ́","Gèlèdé"]},
    {term:"Àyànmọ́",meaning:"Destiny; that which is allotted or chosen as part of a life course.",context:"Often discussed with Orí and Ìpín in Yoruba philosophical thought.",related:["Orí","Ìpín"]},
    {term:"Babaláwo",meaning:"A trained male Ifá specialist.",context:"Literally associated with a father/master of mysteries; training is lineage- and institution-based.",related:["Ifá","Ọ̀pọ́n Ifá"]},
    {term:"Èdè Yorùbá",meaning:"The Yoruba language.",context:"A tonal language spoken in Nigeria, Benin, Togo and global diaspora communities.",related:["Oríkì","Àṣà"]},
    {term:"Ẹ̀mí",meaning:"Breath, spirit or life-force depending on context.",context:"A major concept in discussions of personhood and life.",related:["Orí","Ayé"]},
    {term:"Ẹbọ",meaning:"Offering or ritual sacrifice.",context:"Forms and meanings vary by religious context, lineage and purpose.",related:["Ifá","Òrìṣà"]},
    {term:"Ẹgbẹ́",meaning:"Association, society, group or companion body.",context:"Meaning changes by context, from ordinary associations to spiritual concepts.",related:["Àṣà","Ilé"]},
    {term:"Ewé",meaning:"Leaf; also a broad category of plant material.",context:"Central to herbal, ritual and everyday knowledge.",related:["Ọ̀sányìn","Ìwòsàn"]},
    {term:"Ifá",meaning:"Yoruba divinatory and knowledge system associated with Òrúnmìlà.",context:"Includes Odù, verses, interpretation, ritual and specialist training.",related:["Òrúnmìlà","Odù","Babaláwo"]},
    {term:"Ikin",meaning:"Sacred palm nuts used in Ifá divination.",context:"Handled within trained ritual practice.",related:["Ifá","Ọ̀pọ́n Ifá"]},
    {term:"Ilé",meaning:"House, home, lineage house or place.",context:"Can refer to a physical house or a social/ritual institution.",related:["Ìdílé","Àṣà"]},
    {term:"Ìpín",meaning:"Portion, allotment; often used in discussions of destiny.",context:"Frequently appears alongside Orí and Àyànmọ́.",related:["Orí","Àyànmọ́"]},
    {term:"Ìṣẹ̀ṣe",meaning:"Traditional practice; inherited custom; indigenous religious tradition.",context:"Often used today for Yoruba traditional religion and cultural continuity.",related:["Àṣà","Òrìṣà"]},
    {term:"Ìwà Pẹ̀lẹ́",meaning:"Gentle, balanced or good character.",context:"A major ethical ideal in Yoruba thought and Ifá discourse.",related:["Orí","Àṣẹ"]},
    {term:"Ìwòsàn",meaning:"Healing, treatment or recovery.",context:"Can refer broadly to practices of restoring health and wellbeing.",related:["Ewé","Oogun"]},
    {term:"Iwúre",meaning:"Blessing or prayer of goodwill.",context:"Spoken to invoke or express good outcomes, peace, health and prosperity.",related:["Àṣẹ","Oríkì"]},
    {term:"Odù",meaning:"A principal category within the Ifá corpus.",context:"Odù organize large bodies of verses, narratives and interpretive material.",related:["Ifá","Òrúnmìlà"]},
    {term:"Oogun",meaning:"Medicine, preparation, remedy, charm or working depending on context.",context:"A broad Yoruba word whose meaning changes with use; it may refer to physical medicine or ritual preparations.",related:["Ìwòsàn","Ewé"]},
    {term:"Orí",meaning:"Head; also inner head, personal spiritual principle and seat of destiny.",context:"A central concept in Yoruba philosophy of personhood and destiny.",related:["Àyànmọ́","Ìpín"]},
    {term:"Oríkì",meaning:"Praise poetry or praise names.",context:"Performed to invoke identity, lineage, history, character and social memory.",related:["Àṣà","Èdè Yorùbá"]},
    {term:"Òrìṣà",meaning:"Sacred power or divinity in Yoruba religious traditions.",context:"Individual Òrìṣà have distinct histories, cults, priesthoods and regional forms.",related:["Ìṣẹ̀ṣe","Àṣẹ"]},
    {term:"Ọ̀pẹ̀lẹ̀",meaning:"A divination chain used by trained Ifá specialists.",context:"Used within Ifá consultation; not a decorative symbol.",related:["Ifá","Babaláwo"]},
    {term:"Ọ̀pọ́n Ifá",meaning:"Ifá divination tray.",context:"A carved ritual surface used in consultation and documented extensively in Yoruba art history.",related:["Ifá","Ikin"]},
    {term:"Ọ̀run",meaning:"The spiritual realm, heaven or invisible realm depending on context.",context:"Often contrasted relationally with Ayé, the lived world.",related:["Ayé","Ẹ̀mí"]},
    {term:"Ayé",meaning:"The world; lived human realm.",context:"Used in philosophical, social and religious language.",related:["Ọ̀run","Ẹ̀mí"]},
    {term:"Ajé",meaning:"Wealth, commerce or prosperity depending on tone and context.",context:"Not to be confused automatically with Àjẹ́, a different word and concept.",related:["Ọjà","Owó"]},
    {term:"Ọjà",meaning:"Market.",context:"An important economic and social institution in Yoruba towns and cities.",related:["Ajé","Àṣà"]},
    {term:"Ọba",meaning:"King or ruler.",context:"Used for traditional rulers and in titles across Yoruba political history.",related:["Ilé","Àṣà"]},
    {term:"Ògún",meaning:"Òrìṣà associated with iron, labor, technology and roads.",context:"Not the same word as oogun ('medicine/preparation').",related:["Iron","Òrìṣà"]},
    {term:"Ọ̀ṣun",meaning:"Òrìṣà associated with the Ọ̀ṣun River, fertility, beauty and diplomacy.",context:"Closely linked with the sacred grove at Ọ̀ṣogbo.",related:["Òrìṣà","River"]},
    {term:"Ṣàngó",meaning:"Òrìṣà associated with thunder, kingship and public authority.",context:"Strongly linked with Ọ̀yọ́ history and diasporic traditions.",related:["Òrìṣà","Ọ̀yọ́"]},
    {term:"Èṣù",meaning:"Òrìṣà of mediation, exchange, consequence and crossroads.",context:"Should not simply be translated as 'devil'.",related:["Òrìṣà","Ifá"]},
    {term:"Ọbàtálá",meaning:"Senior Òrìṣà associated with creation, clarity and composure.",context:"Relationships with Òrìṣàńlá and related names vary by tradition.",related:["Òrìṣà","Creation"]},
    {term:"Yemọja",meaning:"Òrìṣà associated with waters, motherhood and protection.",context:"West African and diasporic traditions developed different emphases.",related:["Òrìṣà","Water"]},
    {term:"Ọya",meaning:"Òrìṣà associated with wind, transformation and river traditions.",context:"Regional and diasporic meanings vary.",related:["Òrìṣà","Market"]},
    {term:"Ọ̀sányìn",meaning:"Òrìṣà associated with leaves and specialist herbal knowledge.",context:"Closely connected with ewé and trained plant knowledge.",related:["Ewé","Ìwòsàn"]},
    {term:"Olókun",meaning:"Sacred power associated with deep water, wealth and mystery.",context:"Yoruba and Edo traditions should be distinguished carefully.",related:["Water","Òrìṣà"]}
  ],
  products: [
    {name:"Books & Study Materials",cat:"Books & Study",price:"Browse collection",desc:"Reading materials, study notes and educational publications for Yoruba culture, language and traditional knowledge."},
    {name:"Cultural Materials",cat:"Cultural Materials",price:"Browse collection",desc:"Selected cultural objects and materials presented with clear context, provenance and intended use."},
    {name:"Ewé & Botanical Study",cat:"Educational Resources",price:"Browse collection",desc:"Reference materials for Yoruba plant names, botanical identification and responsible cultural study."},
    {name:"Traditional Craft",cat:"Traditional Craft",price:"Browse collection",desc:"Craft-led pieces inspired by documented Yoruba material culture, presented without invented sacred symbolism."},
    {name:"Language Resources",cat:"Educational Resources",price:"Browse collection",desc:"Tools for studying Yoruba vocabulary, terminology, pronunciation and cultural context."},
    {name:"Isese Ponbele Publications",cat:"Books & Study",price:"Browse collection",desc:"House publications and documentary resources produced for cultural education and reference."}
  ]
};