(async()=>{
const grid=document.getElementById('entryGrid'),filters=document.getElementById('oogunFilters'),count=document.getElementById('resultCount'),search=document.getElementById('catalogueSearch'),pager=document.getElementById('oogunPagination'),summary=document.getElementById('oogunPageSummary'),modal=document.getElementById('detailModal'),modalBody=document.getElementById('modalBody');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s??'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const finish=()=>{document.querySelector('.site-loader')?.classList.add('done');document.body.classList.remove('loading')};setTimeout(finish,900);
const social=t=>{const m=encodeURIComponent(`Hello Isese Ponbele, I am asking about ${t}.`);return `<div class="post-social"><span class="post-social-label">Connect with Isese Ponbele</span><a class="social-btn social-tiktok" href="https://www.tiktok.com/@iseseponbele" target="_blank" rel="noopener noreferrer">TikTok</a><a class="social-btn social-facebook" href="https://www.facebook.com/iseseponbele" target="_blank" rel="noopener noreferrer">Facebook</a><a class="social-btn social-youtube" href="https://www.youtube.com/@iseseponbele" target="_blank" rel="noopener noreferrer">YouTube</a><a class="social-btn social-whatsapp" href="https://wa.me/2347047604452?text=${m}" target="_blank" rel="noopener noreferrer">WhatsApp</a></div>`};
const list=(title,items,ordered=false)=>{if(!items?.length)return'';const tag=ordered?'ol':'ul';return `<div class="formula-block"><h4>${esc(title)}</h4><${tag}>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</${tag}></div>`};
const decompress=async b64=>{if(!b64)return[];if(!('DecompressionStream'in window))throw new Error('This browser cannot open the compressed archive.');const raw=atob(b64),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0)),stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')),text=await new Response(stream).text(),data=JSON.parse(text);return Array.isArray(data)?data:[]};
let entries=[],active='all',q='',page=1;const pageSize=60;
const getMatches=()=>entries.filter(e=>{if(active!=='all'&&slug(e.c||'Other')!==active)return false;if(!q)return true;return `${e.t||''} ${e.m||''} ${e.c||''} ${e.s||''} ${e.pg||''}`.toLowerCase().includes(q)});
const card=e=>{const restricted=e.r?.length,short=e.m||'Traditional Oogun archive entry';return `<article class="entry-card reveal in-view" data-entry-id="${esc(e.q)}"><div class="entry-top"><span class="entry-tag">${esc(e.c||'Other')}</span><span class="entry-id">${esc(e.s||e.q)}</span></div><h3>${esc(e.t||'Untitled entry')}</h3><div class="translation">${esc(short)}</div><p>${restricted?'Independent archive entry':(e.a?.length||e.p?.length||e.u?.length?'Open the formula to view materials, preparation and usage':'Open the record to view its source reference')}</p>${social(e.t||'this entry')}<span class="entry-open">↗</span></article>`};
function renderPager(total){if(!pager||!summary)return;const pages=Math.max(1,Math.ceil(total/pageSize));if(page>pages)page=pages;const nums=[];for(let i=1;i<=pages;i++)if(i===1||i===pages||Math.abs(i-page)<=2)nums.push(i);let html=`<button data-page="${page-1}" ${page===1?'disabled':''}>←</button>`,last=0;for(const n of nums){if(last&&n-last>1)html+='<span>…</span>';html+=`<button data-page="${n}" class="${n===page?'active':''}">${n}</button>`;last=n}html+=`<button data-page="${page+1}" ${page===pages?'disabled':''}>→</button>`;pager.innerHTML=html;const start=total?((page-1)*pageSize+1):0,end=Math.min(page*pageSize,total);summary.textContent=total?`Showing ${start.toLocaleString()}–${end.toLocaleString()} of ${total.toLocaleString()} entries • Page ${page} of ${pages}`:''}
function render(){const matches=getMatches(),start=(page-1)*pageSize,shown=matches.slice(start,start+pageSize);if(grid)grid.innerHTML=shown.map(card).join('');if(count)count.textContent=`${matches.length.toLocaleString()} ${matches.length===1?'entry':'entries'} in catalogue`;document.querySelector('.empty-state')?.style.setProperty('display',matches.length?'none':'block');renderPager(matches.length)}
function refreshFilters(){const cats=[...new Set(entries.map(e=>e.c||'Other'))].sort((a,b)=>a.localeCompare(b)),counts=Object.fromEntries(cats.map(c=>[c,entries.filter(e=>(e.c||'Other')===c).length]));if(filters)filters.innerHTML=[`<button class="filter-btn ${active==='all'?'active':''}" data-filter="all"><span>All formulas</span><span>${entries.length}</span></button>`,...cats.map(c=>`<button class="filter-btn ${active===slug(c)?'active':''}" data-filter="${slug(c)}"><span>${esc(c)}</span><span>${counts[c]}</span></button>`)].join('')}
function openItem(id){const item=entries.find(x=>String(x.q)===String(id));if(!item||!modal||!modalBody)return;const restricted=item.r?.length,src=item.src||'OOGUN BABA OGUN YORUBA TRADITIONAL CHARMS',pg=item.pg?` • PDF page ${item.pg}`:'',details=restricted?'':`${list('Materials needed',item.a)}${list('Preparation',item.p,true)}${list('Usage',item.u,true)}${list('Incantation / Ofo',item.i)}${list('Translation',item.x)}${list('Source notes',item.o)}`;modalBody.innerHTML=`<div class="kicker">Source entry ${esc(item.s||item.q)} • ${esc(item.c||'Other')}</div><h2>${esc(item.t||'Untitled entry')}</h2><div class="translation">${esc(item.m||'Traditional Oogun archive entry')}</div><div class="modal-meta"><span>${esc(item.c||'Other')}</span><span>Independent formula</span></div>${details}<div class="source-line">Source: <em>${esc(src)}</em>${esc(pg)} — wording organized from the supplied source.</div>${social(item.t||'this entry')}`;modal.classList.add('open');document.body.style.overflow='hidden'}
filters?.addEventListener('click',e=>{const b=e.target.closest('.filter-btn[data-filter]');if(!b)return;active=b.dataset.filter;page=1;refreshFilters();render()});search?.addEventListener('input',()=>{q=search.value.trim().toLowerCase();page=1;render()});pager?.addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(!b||b.disabled)return;page=Number(b.dataset.page)||1;render();document.querySelector('.catalogue-toolbar')?.scrollIntoView({behavior:'smooth',block:'start'})});grid?.addEventListener('click',e=>{if(e.target.closest('.post-social a'))return;const c=e.target.closest('.entry-card[data-entry-id]');if(c)openItem(c.dataset.entryId)});
const close=()=>{modal?.classList.remove('open');document.body.style.overflow=''};document.querySelector('.modal-close')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav-links');menu?.addEventListener('click',()=>nav?.classList.toggle('open'));document.querySelector('.back-top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));document.querySelectorAll('.view-toggle button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid?.classList.toggle('list-view',b.dataset.view==='list')}));
try{const [base,extra]=await Promise.all([decompress(window.OOGUN_BASE_GZ||''),decompress(window.OOGUN_EXTRA_GZ||'')]);if(base.length!==220)throw new Error(`Original archive decoded ${base.length} entries instead of 220.`);if(extra.length!==1000)throw new Error(`Expanded archive decoded ${extra.length} entries instead of 1,000.`);entries=[...base,...extra].sort((a,b)=>(Number(a.q)||0)-(Number(b.q)||0));window.OOGUN_ENTRIES=entries;document.querySelectorAll('.hero-badge').forEach(b=>{if(/entries imported/i.test(b.textContent))b.textContent=`${entries.length.toLocaleString()} entries imported`});refreshFilters();render();finish()}catch(err){console.error(err);if(grid)grid.innerHTML='<div class="empty-state" style="display:block">The full Oogun archive could not be opened. Please refresh the page.</div>';if(count)count.textContent='Archive unavailable';finish()}
})();