window.ISESE_ORISA_DATA = [
  {
    "slug": "orunmila",
    "name": "Òrúnmìlà",
    "classification": "Òrìṣà of Ifá, wisdom and divinatory knowledge",
    "short": "Òrúnmìlà stands at the heart of Ifá as a figure of wisdom, counsel, memory and reflection on destiny.",
    "domains": ["Ifá","wisdom","destiny","counsel"],
    "overview": "In Yoruba religious thought, Òrúnmìlà is closely associated with Ifá, the divinatory and literary corpus through which questions of character, choice, consequence and destiny are explored. He is often described in praise and teaching as a witness to human destiny and as a source of unusually deep knowledge. His importance is therefore not only predictive: Ifá is also a moral, historical and philosophical archive.",
    "character": "Òrúnmìlà’s documentary significance lies in the relationship between divination and disciplined interpretation. Babaláwo and other Ifá specialists transmit verses, procedures, histories and ethical lessons through apprenticeship. Consultation is traditionally embedded in speech, memory, ritual discipline and social responsibility rather than being reducible to fortune-telling.",
    "material": "Common visual and material representations include the ọ̀pọ́n Ifá (divination tray), ikin Ifá (sacred palm nuts), ọ̀pẹ̀lẹ̀ (divining chain), ìrókẹ̀ Ifá (tapper) and carved containers or vessels associated with divination. These objects are among the most widely documented Yoruba sacred arts in museum collections.",
    "geography": "Ilé-Ifẹ̀ is especially important in narratives of origins and sacred authority, while Ifá lineages extend across Yorubaland and the wider Yoruba diaspora. Local houses preserve different praise names, emphases and bodies of memorized verse.",
    "variation": "No single modern chart exhausts Òrúnmìlà’s meanings. Lineages can differ in ritual details, terminology and local narratives while sharing the central relationship between Òrúnmìlà and Ifá.",
    "file": "Opon Ifa (Ifa Tray).jpg",
    "refs": [["William Bascom — Ifa Divination: Communication Between Gods and Men in West Africa","https://books.google.com/books?id=XZR-AAAAMAAJ"],["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Metropolitan Museum — Àgéré Ifá","https://www.metmuseum.org/art/collection/search/316595"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Opon_Ifa_(Ifa_Tray).jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Opon%20Ifa%20%28Ifa%20Tray%29.jpg"
  },
  {
    "slug": "esu",
    "name": "Èṣù",
    "classification": "Òrìṣà of mediation, communication, exchange and consequence",
    "short": "Èṣù is a complex mediator whose traditions center communication, crossroads, exchange, choice and the consequences of action.",
    "domains": ["communication","crossroads","exchange","consequence"],
    "overview": "Èṣù occupies a crucial mediating position in Yoruba sacred thought. He is associated with movement between parties, the delivery and testing of messages, exchange, ambiguity, negotiation and the consequences that follow human choices. He appears widely in oral literature and Ifá narratives as an intelligent, active force whose presence prevents moral and ritual life from becoming simplistic.",
    "character": "A central documentary point is that Èṣù is not equivalent to the Christian devil. That equation emerged from missionary translation and later popular misunderstanding. Yoruba materials present a far more complex figure: capable of disruption, but also essential to communication, accountability, sacrifice, interpretation and the working of relationships.",
    "material": "Representations include carved staffs, shrine figures, stones and other locally specific forms. Visual traditions vary greatly by town and lineage. The staff used here is a documented cultural object and should be read as a representation of worship and material culture, not as a literal portrait.",
    "geography": "Èṣù traditions are widespread across Yorubaland and are also central in Afro-Atlantic religions, where names, forms and ritual emphases have developed in different historical environments.",
    "variation": "Colors, numbers, foods, days and iconographic forms are not universally fixed across all Yoruba communities. Lineage context matters.",
    "file": "Esu staff.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Esu_staff.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Esu%20staff.jpg"
  },
  {
    "slug": "ogun",
    "name": "Ògún",
    "classification": "Òrìṣà of iron, technology, roads, labour and disciplined force",
    "short": "Ògún joins iron, work, hunting, roads, technology and danger in a powerful ethic of disciplined force.",
    "domains": ["iron","work","roads","technology"],
    "overview": "Ògún is one of the most widely recognized Yoruba Òrìṣà. He is associated with iron and with the human activities made possible by iron: farming, hunting, building, warfare, transport, craft and technological transformation. His traditions hold together creativity and danger, because the same tool that opens a road or farms a field can also injure.",
    "character": "Documentary study of Ògún often emphasizes responsibility. Power is not celebrated as force alone; it is expected to be controlled, purposeful and socially useful. This helps explain Ògún’s importance to blacksmiths, hunters, drivers, soldiers, artisans and other occupations connected with tools, roads or risk.",
    "material": "Iron implements, forge tools, machetes, staffs and shrine assemblages are common forms of representation. A real shrine photograph is used on this site because it conveys how Ògún is materialized through iron rather than through a standardized fantasy portrait.",
    "geography": "Ògún traditions are widespread throughout Yorubaland and have major diaspora histories in the Caribbean and the Americas. Local cult houses can differ in praise names, ritual objects and festival practice.",
    "variation": "Modern popular color-coding often oversimplifies older local traditions. The strongest constants are iron, work, road-opening, danger and disciplined technological power.",
    "file": "Ogun shrine.jpg",
    "refs": [["Sandra T. Barnes (ed.) — Africa’s Ogun: Old World and New",""] ,["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Ogun_shrine.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ogun%20shrine.jpg"
  },
  {
    "slug": "osun",
    "name": "Ọ̀ṣun",
    "classification": "River Òrìṣà associated with fertility, healing, beauty, diplomacy and prosperity",
    "short": "Ọ̀ṣun is a river Òrìṣà whose living traditions connect fertility, healing, beauty, social intelligence and sacred landscape.",
    "domains": ["river","fertility","healing","diplomacy"],
    "overview": "Ọ̀ṣun is strongly associated with the river that bears her name and with the city of Ọ̀ṣogbo, where the Ọ̀ṣun-Ọ̀ṣogbo Sacred Grove remains an active religious landscape. Her traditions encompass fertility, healing, prosperity, beauty, social grace and the intelligence required to negotiate relationships.",
    "character": "Ọ̀ṣun’s stories frequently challenge any idea that sweetness or beauty means weakness. In oral tradition she can embody strategic intelligence, authority and the necessity of female presence in social and cosmic balance. Public festival culture, ritual specialists and sacred landscape all contribute to her contemporary visibility.",
    "material": "River water, shrine architecture, brass or gold-toned objects, vessels, sculptures and festival regalia can all participate in representations of Ọ̀ṣun. The image used here comes from the sacred-grove environment rather than an invented face.",
    "geography": "The Ọ̀ṣun-Ọ̀ṣogbo Sacred Grove is internationally recognized by UNESCO and remains one of the clearest examples of a living Yoruba sacred landscape organized around an Òrìṣà.",
    "variation": "Ọ̀ṣun traditions extend far beyond Ọ̀ṣogbo and vary by locality and diaspora community. Popular associations should not be treated as a single universal ritual manual.",
    "file": "Osun Osogbo 2026 (Sacred Shrine & Offerings).jpg",
    "refs": [["UNESCO — Osun-Osogbo Sacred Grove","https://whc.unesco.org/en/list/1118/"],["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Osun_Osogbo_2026_(Sacred_Shrine_%26_Offerings).jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Osun%20Osogbo%202026%20%28Sacred%20Shrine%20%26%20Offerings%29.jpg"
  },
  {
    "slug": "sango",
    "name": "Ṣàngó",
    "classification": "Òrìṣà of thunder, lightning, royal authority, performance and justice",
    "short": "Ṣàngó brings together thunder, charisma, royal memory, justice and the performance of power.",
    "domains": ["thunder","kingship","justice","performance"],
    "overview": "Ṣàngó is associated with thunder and lightning and is deeply connected to histories and memories of Ọ̀yọ́ kingship. Yoruba traditions relate sacred power, political authority, performance, drumming, dance and moral consequence through Ṣàngó’s figure.",
    "character": "His documentary importance is both religious and historical. Traditions about Ṣàngó show how royal memory can become sacred memory, and how performance can preserve ideas about legitimate power. Thunder is not merely a weather symbol; it becomes a language of awe, accountability and public authority.",
    "material": "The oshe Ṣàngó, commonly carved with a double-axe form, is among the most recognizable ritual arts associated with Ṣàngó. Staffs, shrine sculptures, drums and red-white performance regalia appear in different settings.",
    "geography": "Ọ̀yọ́ is central to Ṣàngó traditions, but worship extends widely across Yorubaland and the Atlantic world. Historical and ritual emphases vary by community.",
    "variation": "Modern claims that one color, number or offering uniquely defines Ṣàngó everywhere should be treated cautiously. Historical Ọ̀yọ́, priestly lineage and local oral tradition provide more reliable context.",
    "file": "Yoruba Shango.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Yoruba_Shango.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Yoruba%20Shango.jpg"
  },
  {
    "slug": "obatala",
    "name": "Ọbàtálá",
    "classification": "Òrìṣà associated with creation, whiteness, calmness, seniority and moral restraint",
    "short": "Ọbàtálá is linked with creation, white cloth, elder authority, clarity and the disciplined ideal of calm character.",
    "domains": ["creation","clarity","seniority","restraint"],
    "overview": "Ọbàtálá, also called Òrìṣà-nlá in many contexts, occupies a senior place in Yoruba religious thought. He is often associated with the shaping of human form, creation, whiteness, coolness, calmness and ethical restraint.",
    "character": "The ideal of coolness associated with Ọbàtálá is not simply visual. It suggests composure, maturity, patience and the control of destructive excess. This makes his traditions important for understanding the Yoruba moral vocabulary of character and seniority.",
    "material": "White cloth, white beads, staffs, shrine spaces and sculptural forms are frequently associated with Ọbàtálá traditions. The photographed shrine used here emphasizes lived sacred space rather than a single standardized facial image.",
    "geography": "Ọbàtálá traditions are prominent at Ilé-Ifẹ̀ and across many Yoruba communities. Local titles, histories and ritual details differ.",
    "variation": "Ọbàtálá and Òrìṣà-nlá may be treated as identical in some contexts and distinguished in others. The site therefore presents broad orientation rather than declaring one lineage’s taxonomy universal.",
    "file": "The Ancient Obatala Shrine.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:The_Ancient_Obatala_Shrine.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/The%20Ancient%20Obatala%20Shrine.jpg"
  },
  {
    "slug": "yemoja",
    "name": "Yemọja",
    "classification": "Water and motherhood Òrìṣà with major Yoruba and diaspora traditions",
    "short": "Yemọja is a major maternal and water-associated Òrìṣà whose riverine Yoruba histories expanded into powerful oceanic traditions in the diaspora.",
    "domains": ["water","motherhood","lineage","protection"],
    "overview": "Yemọja is associated with motherhood, water and generative continuity. Yoruba traditions often emphasize riverine dimensions, while Atlantic diaspora histories have developed strong oceanic representations. The difference is historically important and shows how Òrìṣà traditions adapt across geography.",
    "character": "Yemọja’s maternal symbolism is not limited to biological motherhood. It can evoke protection, ancestry, lineage continuity, nourishment and the collective power of water as a source of life.",
    "material": "Festival regalia, water vessels, beads, shrine objects and aquatic symbolism are among the many forms through which Yemọja is represented. The site uses a documented Nigerian festival image rather than a fantasy portrait.",
    "geography": "Yemọja worship is present in multiple Yoruba regions and became especially prominent in Brazil, Cuba and other parts of the diaspora, where oceanic symbolism took on expanded significance.",
    "variation": "Spellings and names vary—Yemọja, Yemoja, Yemaya and others—along with ritual forms. Yoruba and diaspora traditions should be related historically without being collapsed into one identical practice.",
    "file": "Yemoja Nigeria.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Yemoja_Nigeria.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Yemoja%20Nigeria.jpg"
  },
  {
    "slug": "oya",
    "name": "Ọya",
    "classification": "Òrìṣà of winds, storms, movement, transformation and river power",
    "short": "Ọya is remembered through wind, storm, movement, courage, river power and radical transformation.",
    "domains": ["wind","storm","transformation","river"],
    "overview": "Ọya is associated with winds, storms and transformation, and in important traditions with the Niger River. Her narratives frequently emphasize speed, courage, change and the ability to move through dangerous transitions.",
    "character": "Ọya’s documentary value lies in the way natural movement becomes a language for social and spiritual change. Wind and storm are not static emblems; they are processes—forces that rearrange, clear, threaten and renew.",
    "material": "Shrines, staffs, textiles and festival representations differ by locality. The photograph used here documents an Ọya shrine in Irra, Kwara State, grounding the page in a real sacred place.",
    "geography": "Irra has notable Ọya traditions, while broader worship extends across Yoruba communities and the diaspora. Associations with cemeteries are especially emphasized in some diaspora traditions and should not automatically be projected unchanged onto every Yoruba locality.",
    "variation": "Descriptions of Ọya vary significantly across regions. The site distinguishes widely repeated themes from claims that belong to specific houses or Atlantic traditions.",
    "file": "Oya Shrine in Oya Grove, Irra, Kwara State, Nigeria 01.jpg",
    "refs": [["Judith Gleason — Oya: In Praise of the Goddess",""] ,["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Oya_Shrine_in_Oya_Grove,_Irra,_Kwara_State,_Nigeria_01.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Oya%20Shrine%20in%20Oya%20Grove%2C%20Irra%2C%20Kwara%20State%2C%20Nigeria%2001.jpg"
  },
  {
    "slug": "osanyin",
    "name": "Ọ̀sányìn",
    "classification": "Òrìṣà of leaves, herbal knowledge and the disciplined intelligence of medicine",
    "short": "Ọ̀sányìn centers ewé—leaves, herbal knowledge, forest intelligence and the disciplined handling of medicine.",
    "domains": ["leaves","medicine","forest knowledge","healing"],
    "overview": "Ọ̀sányìn is closely associated with herbal and leaf knowledge. His traditions emphasize that plants are not interchangeable ingredients: names, habitat, preparation, language, timing and lineage knowledge shape how medicinal and ritual systems are understood.",
    "character": "The importance of Ọ̀sányìn extends beyond a simple label of “healing god.” He represents specialized knowledge and the disciplined relationship between people, plants and speech. In Yoruba thought, ewé can be botanical, medicinal, poetic and sacred at the same time.",
    "material": "The iron Ọ̀sányìn staff, often constructed with a central bird and radiating elements, is one of the most recognizable Yoruba ritual forms. Leaves, containers and shrine assemblages also appear in practice.",
    "geography": "Herbal specialists and Ọ̀sányìn traditions are found across Yorubaland with significant local variation. Plant knowledge is strongly ecological: the same name can shift by locality and not every identification is universal.",
    "variation": "Online lists frequently flatten Yoruba plant traditions. This documentary stresses uncertainty, regional names and the difference between cultural documentation and medical advice.",
    "file": "Osanyin Staff.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Osanyin_Staff.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Osanyin%20Staff.jpg"
  },
  {
    "slug": "olokun",
    "name": "Olókun",
    "classification": "Deep-water sacred power associated with depth, wealth, mystery and abundance",
    "short": "Olókun embodies the depth and hidden abundance of water, with traditions that vary strongly between Yoruba and neighboring cultural histories.",
    "domains": ["deep water","wealth","depth","mystery"],
    "overview": "Olókun is associated with deep water, wealth, hidden abundance and the mysterious depth of the aquatic realm. The name and traditions appear in Yoruba contexts but also have major histories in Edo/Benin religion, making careful regional distinction important.",
    "character": "Depth is a useful interpretive key: Olókun evokes that which is valuable but not immediately visible, powerful but not easily approached. Wealth symbolism often includes the sea, beads, cowries and other signs of abundance.",
    "material": "Water shrines, cowries, beads, vessels and modern cultural monuments are among the representations encountered today. The image used on this site is an Ori Olokun cultural monument in Ilé-Ifẹ̀.",
    "geography": "Ilé-Ifẹ̀ preserves important Olókun associations, while Benin/Edo traditions have their own highly developed Olókun histories. The page avoids merging these into a single undifferentiated account.",
    "variation": "Gender, genealogy and ritual attributes vary by region and diaspora community. This variability should be treated as historical evidence rather than as an error to be corrected.",
    "file": "Ori Olokun Sculpture 02.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Metropolitan Museum — Owo/Benin historical context","https://www.metmuseum.org/ja/essays/origins-and-empire-the-benin-owo-and-ijebu-kingdoms"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Ori_Olokun_Sculpture_02.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ori%20Olokun%20Sculpture%2002.jpg"
  },
  {
    "slug": "orisa-oko",
    "name": "Òrìṣà Oko",
    "classification": "Agricultural Òrìṣà associated with cultivated land, farming, fertility and social order",
    "short": "Òrìṣà Oko joins cultivated land, farming, food production, fertility and the social dignity of productive labour.",
    "domains": ["agriculture","land","fertility","food"],
    "overview": "Òrìṣà Oko is associated with agriculture, cultivated land, farming and the fertility of fields. His traditions remind us that sacred life in agrarian societies is deeply connected to food production, weather, soil and the moral value of labour.",
    "character": "Rather than treating agriculture as ordinary and spirituality as separate, Òrìṣà Oko traditions show how subsistence, prosperity and community continuity can be religious concerns. Farming links households to seasons, ancestors, markets and collective survival.",
    "material": "Iron staffs and sheaths associated with Òrìṣà Oko are documented in museum collections. The object used here comes from a documented Yoruba context in the Ọ̀yọ́ region and provides a material anchor for the page.",
    "geography": "Traditions vary across farming communities and regions. Some houses emphasize fertility, others social justice, land or agricultural abundance.",
    "variation": "Modern summaries often attach one simplified function. Historical objects and oral traditions show a broader relationship to cultivated land and communal wellbeing.",
    "file": "Staff and sheath for Orisha Oko, Yoruba peoples, Oyo region, Irawo village, Nigeria, Late 19th to early 20th century, Staff iron, wood (2923635450).jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Staff_and_sheath_for_Orisha_Oko,_Yoruba_peoples,_Oyo_region,_Irawo_village,_Nigeria,_Late_19th_to_early_20th_century,_Staff_iron,_wood_(2923635450).jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Staff%20and%20sheath%20for%20Orisha%20Oko%2C%20Yoruba%20peoples%2C%20Oyo%20region%2C%20Irawo%20village%2C%20Nigeria%2C%20Late%2019th%20to%20early%2020th%20century%2C%20Staff%20iron%2C%20wood%20%282923635450%29.jpg"
  },
  {
    "slug": "erinle",
    "name": "Erinlẹ̀",
    "classification": "Riverine and hunting Òrìṣà associated with healing, water and forest knowledge",
    "short": "Erinlẹ̀ is a riverine and hunting power whose traditions connect water, healing, forest knowledge and local sacred geography.",
    "domains": ["river","hunting","healing","forest"],
    "overview": "Erinlẹ̀ has important local traditions, particularly in parts of Ọ̀ṣun State and neighboring areas, and is associated with riverine power, hunting and healing. In the diaspora the name may appear as Inle or Inlé, often with transformed ritual emphases.",
    "character": "Erinlẹ̀ demonstrates why Yoruba religion cannot be understood only through a short list of globally famous Òrìṣà. Local rivers, towns and priestly lineages preserve sacred powers whose importance may be enormous in one region even when less visible internationally.",
    "material": "Sculpture, shrine forms, river imagery and hunting symbols appear in representations. The image used here is a documented cultural representation labeled Ibualama/Inle in museum-oriented sources.",
    "geography": "Ilobu and related riverine traditions are often mentioned in accounts of Erinlẹ̀. Local oral histories should be prioritized when reconstructing specific ritual genealogies.",
    "variation": "Diaspora forms may preserve the name while reorganizing relationships with other Òrìṣà. The page distinguishes Yoruba regional context from later Atlantic developments.",
    "file": "Ibualama.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Ibualama.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ibualama.jpg"
  },
  {
    "slug": "iyami-aje",
    "name": "Ìyámi Àjẹ́",
    "classification": "The Mothers / Àjẹ́ — a sacred-power complex whose classification varies by lineage",
    "short": "Ìyámi Àjẹ́ and Àwọn Ìyá express powerful Yoruba ideas about elder women, Àjẹ́, social balance, birds, secrecy and female spiritual authority.",
    "domains": ["Àjẹ́","the Mothers","female authority","Gèlèdé"],
    "overview": "Ìyámi Àjẹ́ is included in this sacred-powers directory because many practitioners speak of the Mothers in a way that places them centrally within Yoruba sacred life. At the same time, lineages and scholars differ on whether Àwọn Ìyá or Àjẹ́ should be classified exactly like one named Òrìṣà. That variation is itself important documentary evidence.",
    "character": "The category concerns more than the English word “witch.” Àjẹ́ can refer to potent capacity associated especially—but not exclusively in every interpretation—with women, elderhood, fertility, social regulation and the ability to bless or harm. Respect, balance and careful speech are recurring themes.",
    "material": "Bird imagery, carved Gèlèdé masks, performance, shrine forms and the public honoring of elder women are major visual routes into this subject. Gèlèdé is especially important because it gives artistic and social form to the recognition of powerful Mothers.",
    "geography": "Gèlèdé traditions are especially strong among Yoruba-Nago communities across Nigeria, Benin and Togo. UNESCO recognizes the Oral Heritage of Gèlèdé as intangible cultural heritage.",
    "variation": "Terminology is sensitive. Ìyámi, Àwọn Ìyá, Àjẹ́ and Ìyá Nlá overlap in some discourse but are not always interchangeable. The dedicated documentary on this site treats those distinctions in depth.",
    "file": "WLA_ima_Yoruba_cap_mask_for_Gelende_masquerade.jpg",
    "dedicated": "iyami-aje.html",
    "refs": [["UNESCO — Oral heritage of Gèlèdé","https://ich.unesco.org/en/RL/oral-heritage-gelede-00002"],["Henry & Margaret Drewal — Gèlèdé: Art and Female Power among the Yoruba",""] ,["Oyeronke Olajubu — Women in the Yoruba Religious Sphere",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:WLA_ima_Yoruba_cap_mask_for_Gelende_masquerade.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/WLA_ima_Yoruba_cap_mask_for_Gelende_masquerade.jpg"
  },
  {
    "slug": "obaluaye",
    "name": "Ọbalúayé / Ṣọ̀pọ̀nná",
    "classification": "Òrìṣà associated with epidemic disease, affliction, healing and collective responsibility",
    "short": "Ọbalúayé / Ṣọ̀pọ̀nná traditions confront disease, healing, fear, social responsibility and the dangerous power of epidemics.",
    "domains": ["disease","healing","public health memory","affliction"],
    "overview": "Ọbalúayé—often linked in Yoruba materials with Ṣọ̀pọ̀nná and in diaspora traditions with Omolu or related names—is associated with epidemic disease, affliction and healing. Historically, smallpox made these traditions socially powerful and politically sensitive.",
    "character": "The documentary importance of this Òrìṣà is historical as well as religious. Colonial governments attempted to regulate or suppress smallpox-related priesthoods, while communities retained their own understandings of disease, responsibility and sacred danger. The resulting archives must be read critically because colonial reports often portrayed indigenous specialists through hostile assumptions.",
    "material": "Covered shrine forms, raffia-related representations and the xaxará in Afro-Brazilian traditions are common visual associations. The image used here is a photographed ritual object from an Atlantic tradition and is clearly labeled as such, rather than presented as the only Yoruba form.",
    "geography": "Yoruba Ṣọ̀pọ̀nná traditions and Atlantic Ọbalúayé/Omolu traditions are historically related but not identical. Local names and ritual structures vary significantly.",
    "variation": "Because this sacred power is connected with serious disease, the page is historical and cultural documentation only. It does not offer medical treatment or ritual instructions.",
    "file": "Xaxará, objeto dos orixas obaluaye, sapata, omolu..JPG",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Historical scholarship on Ṣọ̀pọ̀nná and smallpox in Yorubaland",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Xaxar%C3%A1,_objeto_dos_orixas_obaluaye,_sapata,_omolu..JPG"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Xaxar%C3%A1%2C%20objeto%20dos%20orixas%20obaluaye%2C%20sapata%2C%20omolu..JPG"
  },
  {
    "slug": "ibeji",
    "name": "Ìbejì",
    "classification": "Sacred twins and the spiritual complex surrounding twin birth",
    "short": "Ìbejì traditions honor twins as extraordinary beings and preserve one of the most distinctive forms of Yoruba sacred art: ere ìbejì.",
    "domains": ["twins","family","fortune","memorial art"],
    "overview": "Yoruba communities are widely known for a high incidence of twin births and for the special sacred status accorded to twins. Ìbejì traditions concern living twins, family responsibility, fortune and the continuing relationship with a twin who has died.",
    "character": "Museum collections preserve many ere ìbejì: carved memorial figures that can serve as points of relationship with a deceased twin. These figures are not merely “dolls.” Historical descriptions record washing, dressing, feeding and adorning them as part of family care.",
    "material": "Ere ìbejì are among the most recognizable Yoruba sculptural traditions. Wood, beads, cowries, camwood and textile may be used, and regional carving styles can often be distinguished by specialists.",
    "geography": "Ìbejì traditions occur throughout Yorubaland, with important regional styles including Ọ̀yọ́, Ìjẹ̀bú, Ìgbómìnà, Ekiti and others.",
    "variation": "Not every family handles twin traditions identically. Museum objects should be understood as evidence of lived family relationships rather than as standardized religious icons.",
    "file": "Twin figure (ere ibeji), Yoruba people, Southwestern Nigeria, early 20th century AD, wood, beads - Krannert Art Museum, UIUC - DSC06171.jpg",
    "refs": [["Metropolitan Museum — Twin Figure (Ibeji)","https://www.metmuseum.org/art/collection/search/311121"],["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Twin_figure_(ere_ibeji),_Yoruba_people,_Southwestern_Nigeria,_early_20th_century_AD,_wood,_beads_-_Krannert_Art_Museum,_UIUC_-_DSC06171.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Twin%20figure%20%28ere%20ibeji%29%2C%20Yoruba%20people%2C%20Southwestern%20Nigeria%2C%20early%2020th%20century%20AD%2C%20wood%2C%20beads%20-%20Krannert%20Art%20Museum%2C%20UIUC%20-%20DSC06171.jpg"
  },
  {
    "slug": "aje",
    "name": "Ajé",
    "classification": "Òrìṣà / sacred power of wealth, trade, money and the capacity to prosper",
    "short": "Ajé personifies wealth and the capacity for prosperity, especially in relation to trade, markets, money and productive exchange.",
    "domains": ["wealth","trade","markets","prosperity"],
    "overview": "Ajé is a Yoruba sacred power associated with wealth, money, trade and the capacity to prosper. In some contexts Ajé is addressed as an Òrìṣà; in others the term also operates more broadly as the concept of wealth itself. This overlap between personified sacred power and abstract value is characteristic of many Yoruba religious categories.",
    "character": "Ajé traditions connect prosperity to social exchange rather than to isolated accumulation. Markets, labor, opportunity, reputation and relationship all matter. Yoruba thought also distinguishes wealth from good character, reminding us that prosperity without ìwà is not necessarily a complete good life.",
    "material": "Cowries, money containers, market imagery and shrine objects can represent Ajé. The image used here comes from a documented representation of Ajé Shalunga; it should be read as one visual tradition among several.",
    "geography": "Ajé traditions are especially meaningful in commercial towns and market culture, but references appear widely across Yorubaland and the diaspora.",
    "variation": "Ajé, Ajé Ṣàlùgà and related names can be organized differently across houses. The site does not impose a single genealogy on all lineages.",
    "file": "Aje Shalunga.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Yoruba Wikimedians — Orìṣà Ajé audiovisual documentation","https://commons.wikimedia.org/wiki/File:Or%C3%AC%E1%B9%A3%C3%A0_Aj%C3%A9.webm"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Aje_Shalunga.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Aje%20Shalunga.jpg"
  },
  {
    "slug": "logun-ede",
    "name": "Lógun Ẹ̀dẹ",
    "classification": "River-and-forest Òrìṣà associated in many traditions with youth, beauty, hunting and Ọ̀ṣun",
    "short": "Lógun Ẹ̀dẹ brings river and forest imagery together and is widely associated with youth, beauty, hunting and the Ọ̀ṣun tradition.",
    "domains": ["river","forest","youth","hunting"],
    "overview": "Lógun Ẹ̀dẹ is especially prominent in Yoruba and Afro-Brazilian traditions that connect hunting, river power, beauty and youth. Narratives often position Lógun Ẹ̀dẹ in relation to Ọ̀ṣun and hunter traditions, though genealogies and attributes vary.",
    "character": "The figure is useful for understanding how Yoruba sacred identities can cross domains that modern summaries try to keep separate. Forest and water, masculine and feminine-coded aesthetics, hunting and elegance can coexist rather than forming rigid opposites.",
    "material": "Representations may draw on hunting equipment, river symbolism, fine textiles and youthful regalia. The image used here is a documented visual representation from an Atlantic context and is labeled as a representation, not a historical portrait.",
    "geography": "Knowledge of Lógun Ẹ̀dẹ is strong in parts of Yorubaland and has developed a major visual life in Brazil. Atlantic traditions should be compared historically, not treated as exact copies.",
    "variation": "Stories about parentage, gendered presentation and seasonal residence differ significantly. This page records recurring themes without presenting one version as universal.",
    "file": "Logun Ede.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Wikimedia Commons — Logun Ede visual representation","https://commons.wikimedia.org/wiki/File:Logun_Ede.jpg"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Logun_Ede.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logun%20Ede.jpg"
  },
  {
    "slug": "osoosi",
    "name": "Ọ̀ṣọ́ọ̀sí",
    "classification": "Hunter Òrìṣà associated with tracking, accuracy, forest knowledge and provision",
    "short": "Ọ̀ṣọ́ọ̀sí is a hunter Òrìṣà whose traditions emphasize tracking, accuracy, forest intelligence and the search for what is needed.",
    "domains": ["hunting","accuracy","forest","provision"],
    "overview": "Ọ̀ṣọ́ọ̀sí is associated with hunting, the forest, skillful tracking and accuracy. Hunter traditions have long been important in Yoruba society not only for obtaining meat but also for knowledge of territory, plants, danger and movement beyond settled space.",
    "character": "The hunter is a figure of perception: seeing signs, reading terrain, knowing when to move and when to wait. These values make Ọ̀ṣọ́ọ̀sí a useful sacred language for focus, provision and disciplined search.",
    "material": "The bow-and-arrow form known as ofá is a widely recognized representation in Atlantic Òrìṣà traditions. Hunting tools, forest imagery and shrine forms also appear. The site uses a photographed ofá symbol as a real material representation.",
    "geography": "Hunter cults and related Òrìṣà traditions vary widely across Yorubaland. Ọ̀ṣọ́ọ̀sí became especially prominent in several diaspora religions.",
    "variation": "Diaspora iconography is often more standardized than Yoruba local practice. The page therefore distinguishes a recognizable modern symbol from the full range of historical hunter traditions.",
    "file": "Ofá.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Wikimedia Commons — Ofá, Ọ̀ṣọ́ọ̀sí symbol","https://commons.wikimedia.org/wiki/File:Of%C3%A1.jpg"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Of%C3%A1.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Of%C3%A1.jpg"
  },
  {
    "slug": "oba",
    "name": "Ọbà",
    "classification": "River Òrìṣà associated with marriage narratives, endurance, dignity and sacrifice",
    "short": "Ọbà is a river Òrìṣà whose narratives explore marriage, rivalry, dignity, endurance and the costs of devotion.",
    "domains": ["river","marriage","endurance","dignity"],
    "overview": "Ọbà is associated with a river and appears in well-known narratives involving Ṣàngó and other female Òrìṣà. These stories have often been retold as simple jealousy tales, but they also provide material for thinking about marriage, rivalry, self-sacrifice, dignity and the social expectations placed on women.",
    "character": "A documentary approach avoids reducing Ọbà to a single dramatic episode. River identity, local worship and female sacred authority are equally important. Oral versions can differ sharply in tone and moral emphasis.",
    "material": "River imagery, shrine forms and ceremonial representations vary by locality. The image used here is a photographed Atlantic representation of Orixá Obá; the page labels it as diaspora visual culture rather than claiming it is a universal Yoruba icon.",
    "geography": "Ọbà traditions exist in Yorubaland and developed distinctive forms in Brazil and other Atlantic communities.",
    "variation": "Popular internet retellings often homogenize the narrative. This page keeps attention on oral variation and the difference between story, ritual identity and later artistic representation.",
    "file": "Orixá Oba.jpg",
    "refs": [["Drewal, Pemberton & Abiodun — Yoruba: Nine Centuries of African Art and Thought",""] ,["Wikimedia Commons — Orixá Obá representation","https://commons.wikimedia.org/wiki/File:Orix%C3%A1_Oba.jpg"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Orix%C3%A1_Oba.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Orix%C3%A1%20Oba.jpg"
  },
  {
    "slug": "oduduwa",
    "name": "Odùduwà",
    "classification": "Deified ancestor / sacred founder central to Ilé-Ifẹ̀ and Yoruba kingship traditions",
    "short": "Odùduwà stands at the intersection of sacred ancestry, Ilé-Ifẹ̀, political legitimacy and the origin narratives of many Yoruba dynasties.",
    "domains": ["ancestry","kingship","Ile-Ife","origins"],
    "overview": "Odùduwà is one of the most important figures in Yoruba origin traditions. In many accounts Odùduwà is the founder or organizing ancestor of Ilé-Ifẹ̀ and the source of royal dynasties across Yorubaland. The figure therefore sits between sacred ancestry, history, political legitimacy and cosmology.",
    "character": "Different narratives describe Odùduwà in different ways: as a culture hero, founder, ancestor, ruler or sacred being. Rather than forcing these accounts into one modern biography, documentary study asks what each version says about community identity and authority.",
    "material": "Modern statues, palace representations, crowns and royal ritual all contribute to Odùduwà’s public image. The photograph used here shows a statue in Ilé-Ifẹ̀ and should be understood as a modern commemorative representation.",
    "geography": "Ilé-Ifẹ̀ is the central sacred and historical landscape for Odùduwà traditions. Many Yoruba royal houses trace political legitimacy to Ifẹ̀ through genealogies associated with Odùduwà.",
    "variation": "Origin stories vary and can carry political stakes. The page presents multiple traditions as traditions rather than claiming that one oral version is modern historical proof.",
    "file": "The Statue of Oduduwa Ile-Ife 04.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Wikimedia Commons — Statue of Oduduwa, Ilé-Ifẹ̀","https://commons.wikimedia.org/wiki/File:The_Statue_of_Oduduwa_Ile-Ife_04.jpg"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:The_Statue_of_Oduduwa_Ile-Ife_04.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/The%20Statue%20of%20Oduduwa%20Ile-Ife%2004.jpg"
  },
  {
    "slug": "oranmiyan",
    "name": "Òrànmíyàn",
    "classification": "Warrior-ancestor and royal founder associated with Ifẹ̀ and Ọ̀yọ́ political memory",
    "short": "Òrànmíyàn is remembered as a warrior and royal founder whose traditions connect Ilé-Ifẹ̀, conquest, dynasty and the making of Ọ̀yọ́.",
    "domains": ["warrior ancestry","kingship","Oyo","dynasty"],
    "overview": "Òrànmíyàn is a major heroic and dynastic figure in Yoruba history and sacred memory. Traditions associate him with Ilé-Ifẹ̀ and with the establishment or early history of Ọ̀yọ́, making him important to narratives of royal expansion and political identity.",
    "character": "Like Odùduwà, Òrànmíyàn occupies a space where sacred ancestry and historical memory overlap. Oral traditions preserve deeds, journeys and dynastic relationships that have helped communities explain the legitimacy and character of kingship.",
    "material": "The Òrànmíyàn staff at Ilé-Ifẹ̀ is an important monument associated with his memory. The photographed stone monument used here provides a real geographical representation rather than a fantasy warrior portrait.",
    "geography": "Ilé-Ifẹ̀ and Ọ̀yọ́ are central to Òrànmíyàn narratives. The traditions also intersect with wider regional histories of monarchy and migration.",
    "variation": "Chronology and genealogy differ across oral and written sources. Documentary treatment therefore distinguishes sacred-historical memory from the narrower standards of modern archival biography.",
    "file": "Oranmiyan staff.jpg",
    "refs": [["Jacob K. Olupona — City of 201 Gods","https://www.ucpress.edu/books/city-of-201-gods/paper"],["Wikimedia Commons — Òrànmíyàn staff","https://commons.wikimedia.org/wiki/File:Oranmiyan_staff.jpg"],["Image source — Wikimedia Commons","https://commons.wikimedia.org/wiki/File:Oranmiyan_staff.jpg"]],
    "image": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Oranmiyan%20staff.jpg"
  }
];
