const P=[
[1,'Ogbe','Èjì Ogbè','1111',3,'opening, clarity and expansion','visibility, opportunity and clean beginnings','overconfidence or careless haste','move openly and use the opportunity with discipline','fast when the path is kept simple'],
[2,'Oyeku','Ọ̀yẹ̀kú','0000',-2,'closure, hidden matters and deep transition','protection, completion and listening','fear, secrecy or forcing what needs to change','finish unfinished business and protect what remains hidden','slow until the hidden part becomes clear'],
[3,'Iwori','Ìwòrì','0110',0,'inquiry, inward examination and discovery','investigation and seeing what others overlook','suspicion or acting before facts are complete','verify details and ask the second question','moderate and dependent on information'],
[4,'Odi','Òdí','1001',-1,'boundaries, containment and guarded stability','structure, privacy and protection','restriction, stubbornness or isolation','strengthen boundaries without closing every door','slow but capable of stability'],
[5,'Irosun','Ìrosùn','1100',0,'lineage, reputation and remembered consequences','history, family memory and experience','old issues, gossip or repeated patterns','protect your name and correct the repeating pattern','moderate; the past must be handled'],
[6,'Owonrin','Ọ̀wọ̀nrín','0011',-1,'movement, reversal and unstable change','adaptability and unexpected openings','confusion, reversals or unreliable promises','keep a second plan and stay flexible','quick but changeable'],
[7,'Obara','Ọ̀bàrà','1000',1,'speech, negotiation and social influence','persuasion, networking and agreement','careless words, pride or oversharing','speak deliberately and make agreements clear','moderate to fast through communication'],
[8,'Okanran','Ọ̀kànràn','0001',-2,'heat, urgency, friction and pressure','courage to confront a real problem','anger, impulsive action or quarrel','cool the situation before deciding','immediate pressure; better with restraint'],
[9,'Ogunda','Ògúndá','1110',1,'work, struggle and earned victory','strength, persistence and practical effort','force, fatigue or unnecessary battle','remove the real obstruction and do the hard work','progress through sustained effort'],
[10,'Osa','Ọ̀sá','0111',-1,'transformation, unseen influence and sudden shifts','deep change and spiritual sensitivity','instability, fear or dramatic reaction','stabilize yourself and observe what is changing','unpredictable and capable of quick change'],
[11,'Ika','Ìká','0101',-2,'opposition, complexity and careful survival','alertness and strategic patience','intrigue, mistrust or escalation','reduce exposure and choose allies carefully','delayed by complexity or opposition'],
[12,'Oturupon','Òtúrúpọ̀n','1010',0,'correction, accountability and rebuilding','repair and the chance to restore order','repeating an error or refusing correction','correct the sequence and rebuild properly','improves after correction'],
[13,'Otura','Òtúrá','1101',2,'wisdom, planning, counsel and uplift','strategy, learning and sound guidance','plans without execution or ignored advice','choose the sensible path and execute the plan','steady improvement through planning'],
[14,'Irete','Ìretè','0010',1,'persistence, order and gradual consolidation','endurance and patient building','delay, frustration or abandoning a sound process','continue the sound process and measure progress','slow but dependable'],
[15,'Ose','Ọ̀ṣẹ́','1011',2,'attraction, diplomacy and prosperity','favour, relationships and support','flattery, indulgence or appearance without substance','use diplomacy but secure the substance','favour can come quickly through people'],
[16,'Ofun','Òfún','0100',2,'completion, maturity, blessing and consequence','fulfilment, completion and senior wisdom','excess, pride or overextension','finish properly and protect the result from excess','mature results, often later rather than early']
].map(([rank,name,display,bits,score,core,gift,risk,action,tempo])=>({rank,name,display,bits,score,core,gift,risk,action,tempo}));
const B=Object.fromEntries(P.map(x=>[x.bits,x]));const $=s=>document.querySelector(s);let current=null,sound=true,ml=[1,1,1,1],mr=[1,1,1,1],manualTopic=null;
const TOPICS={
 general:{label:'GENERAL',support:'clarity, disciplined conduct and correct timing',block:'confusion, excess or ignoring the secondary condition',step:'reduce the matter to the next concrete decision'},
 money:{label:'MONEY',support:'clear value, controlled spending, sound terms and useful exchange',block:'hidden costs, risky promises, emotional spending or debt pressure',step:'verify the numbers and protect cash flow before committing'},
 work:{label:'WORK / BUSINESS',support:'competence, visible value, consistent effort and clear agreements',block:'unclear roles, rivalry, burnout or forcing an unready structure',step:'define the objective and do the highest-value practical work first'},
 love:{label:'LOVE / RELATIONSHIP',support:'honesty, reciprocity, emotional steadiness and behaviour matching words',block:'mixed signals, pride, secrecy or old resentment',step:'judge behaviour, speak clearly and protect mutual respect'},
 family:{label:'FAMILY',support:'responsibility, respect and wise use of shared history',block:'old grievances, gossip or taking sides too quickly',step:'address the actual issue and lower the emotional heat'},
 travel:{label:'TRAVEL / MOVEMENT',support:'verified arrangements, preparation and flexible timing',block:'rushed planning, unstable transport or missing information',step:'confirm documents, timing, transport and a contingency plan'},
 conflict:{label:'CONFLICT / OPPOSITION',support:'evidence, restraint, boundaries and strategic allies',block:'anger, public escalation, loose speech or hidden rivalry',step:'document facts and use the least destructive effective action'},
 spiritual:{label:'SPIRITUAL MATTER',support:'disciplined observance, clean conduct and careful reflection',block:'fear, obsession with hidden enemies or neglect of practical causes',step:'follow a sound lineage process and separate fear from evidence'},
 health:{label:'HEALTH / WELLBEING',support:'rest, timely assessment and consistent professional care',block:'delay in seeking care, self-diagnosis or stopping treatment',step:'use the reading only for reflection and seek qualified clinical care'}
};
const K={money:/\b(money|cash|debt|loan|profit|pay|finance|salary|wealth|income|fund|investment)\b/i,work:/\b(work|job|career|business|client|contract|promotion|project|employment|company|deal|interview)\b/i,love:/\b(love|relationship|marry|marriage|husband|wife|girlfriend|boyfriend|partner|dating|cheat|romance)\b/i,family:/\b(family|mother|father|parent|child|brother|sister|relative|household)\b/i,travel:/\b(travel|trip|journey|flight|visa|abroad|relocate|road|vehicle|airport)\b/i,conflict:/\b(enemy|opposition|fight|court|dispute|attack|gossip|rival|against me|threat)\b/i,spiritual:/\b(spirit|spiritual|ifa|orisa|ancestor|egun|curse|epe|witch|aje|ebo|destiny|ori|ayanmo)\b/i,health:/\b(health|sick|ill|pain|disease|hospital|doctor|medicine|pregnan|blood|fever|cough|healing)\b/i};
function seed(bit,leg,i){const e=document.createElement('div');e.className='seed '+(bit?'single':'double');e.dataset.leg=leg;e.dataset.i=i;return e}function makeChain(){const c=$('#chain');c.querySelectorAll('.col').forEach(e=>e.remove());['left','right'].forEach(leg=>{const d=document.createElement('div');d.className='col';for(let i=0;i<4;i++)d.appendChild(seed(1,leg,i));c.appendChild(d)})}function marks(bits){return [...bits].map(b=>b==='1'?'I':'II')}function secure(){const a=new Uint8Array(8);crypto.getRandomValues(a);return [...a].map(v=>v<128?0:1)}function fullname(r,l){if(r.bits===l.bits)return r.rank===1?'Èjì Ogbè':`${r.display} Méjì`;return `${r.display} ${l.display}`}function rows(r,l){const a=marks(r),b=marks(l);return a.map((x,i)=>`${x.padEnd(2)}  ${b[i]}`).join('\n')}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function hash(s){let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function detectTopic(q){if(manualTopic)return manualTopic;for(const[t,re]of Object.entries(K))if(re.test(q))return t;return'general'}function yesNo(q){return /^(will|would|can|could|should|is|are|am|do|does|did|has|have|had|may|might|shall|was|were)\b/i.test(q.trim())||/\b(will i|is it|should i|can i|will this|does this|going to)\b/i.test(q)}
function score(c,t){let s=c.right.score*1.25+c.left.score*.8;const ones=(c.rightBits+c.leftBits).split('').filter(x=>x==='1').length;s+=(ones-4)*.28;if(c.right.rank===c.left.rank)s+=c.right.score>=0?.45:-.45;const A={money:{Ogbe:.5,Ose:.5,Otura:.4,Irete:.3,Okanran:-.5,Ika:-.5},work:{Ogunda:.6,Otura:.5,Irete:.45,Ogbe:.4,Owonrin:-.35},love:{Ose:.7,Obara:.45,Ofun:.35,Okanran:-.6,Ika:-.45},travel:{Owonrin:.3,Ogbe:.3,Okanran:-.45,Odi:-.35},conflict:{Ogunda:.25,Otura:.3,Ika:-.35,Okanran:-.45},family:{Irosun:.35,Ofun:.35,Ose:.3,Okanran:-.45},spiritual:{Otura:.25,Okanran:-.3},health:{Irete:.3,Otura:.25,Okanran:-.4,Owonrin:-.25}}[t]||{};return s+(A[c.right.name]||0)+(A[c.left.name]||0)*.55}
function band(s,yn){if(yn){if(s>=3)return['positive','YES · STRONGLY FAVOURABLE','Yes — the cast supports the matter, especially if you act cleanly and promptly.'];if(s>=1)return['positive','YES · WITH CONDITIONS','Yes, but not carelessly — the result depends on respecting the condition shown by the secondary leg.'];if(s>-1)return['neutral','NOT YET CLEAR','The answer is not a clean yes or no yet; one unresolved factor still has power over the outcome.'];if(s>-3)return['negative','NOT YET · CAUTION','Not yet — correction, patience or protection should come before trying to secure the result.'];return['negative','NO · UNFAVOURABLE NOW','No, not in the present condition — forcing it now is more likely to increase difficulty than produce a clean result.']}if(s>=3)return['positive','STRONGLY SUPPORTIVE','The road is open, but it still requires correct action.'];if(s>=1)return['positive','FAVOURABLE WITH CONDITIONS','There is support in the matter, provided you handle the conditions shown by the cast.'];if(s>-1)return['neutral','MIXED / DEVELOPING','The matter is not settled; the deciding factor is how you manage the tension between both legs.'];if(s>-3)return['negative','CAUTION / DELAY','Correct the blocking condition before pushing for the result.'];return['negative','STRONGLY CAUTIONARY','The present condition is against forcing the matter; protection and correction come before expansion.']}
function coreReading(c,t,b){const T=TOPICS[t],r=c.right,l=c.left;const contrast=Math.abs(r.score-l.score);const lead=`${r.display} leads with ${r.core}. ${l.display} sits underneath with ${l.core}. `+(r.rank===l.rank?'The repeated pattern concentrates the message and should be taken seriously.':contrast>=3?'The legs pull in different directions, so managing the contradiction is central to the answer.':'The two legs form a layered message rather than a complete contradiction.');return{lead,main:`For this ${T.label.toLowerCase()} question, the primary force is ${r.core}. Progress comes through ${r.gift}. The underlying leg warns about ${l.risk}. This is why the orientation is “${b[1].toLowerCase()}”: the opportunity and caution are both active.`,right:`${r.display} is the leading leg and describes the visible or immediate force: ${r.core}. Its useful side is ${r.gift}. Its timing is ${r.tempo}.`,left:`${l.display} is the underlying leg and describes a secondary condition, hidden influence or consequence. Watch especially for ${l.risk}. Its timing is ${l.tempo}.`,supportTitle:`Use the strength of ${r.display}`,support:`${T.support}. In this cast, ${r.display} supports the matter through ${r.gift}.`,blockTitle:`${l.display} shows the main caution`,block:`${T.block}. ${l.display} adds a specific warning against ${l.risk}.`,actionTitle:t==='health'?'Use the reading for reflection, not diagnosis':t==='spiritual'?'Follow a disciplined lineage process':'Turn the reading into one controlled next move',action:`${T.step}. Cast-specific instruction: ${r.action}; at the same time, ${l.action}.`,deep:`Read the pair as a sequence. First ${r.display} asks you to deal with ${r.core}; then ${l.display} shows what sits behind the matter as ${l.core}. A better result comes from using the constructive side of the first leg while deliberately controlling the caution in the second. ${t==='spiritual'?'For Ibọ̀, ẹbọ, Ese Ifá or lineage-specific ritual prescriptions, use the procedures of your own lineage rather than treating this software layer as the authority.':''}`}}
function ext(c,t){try{const a=window.OPELE_EXPANDED?.entries?.[String(c.number)]?.[t];return Array.isArray(a)&&a.length?a[hash(c.question+'|'+c.number+'|'+t)%a.length]:null}catch{return null}}function build(c){const t=detectTopic(c.question),s=score(c,t),b=band(s,yesNo(c.question));let x=coreReading(c,t,b),e=ext(c,t);if(e)x={...x,...e};return{topic:t,score:s,band:{cls:b[0],label:b[1],headline:b[2]},...x}}
function cast(leftBits,rightBits,source='digital'){const l=B[leftBits],r=B[rightBits];if(!l||!r)return;const q=$('#question').value.trim();if(!q){toast('Write your question first');$('#question').focus();return}const c={id:Date.now(),leftBits,rightBits,left:l,right:r,name:fullname(r,l),number:(r.rank-1)*16+l.rank,type:r.bits===l.bits?'Odù Méjì':'Odù Amúlù',question:q,source,time:new Date().toISOString()};c.reading=build(c);current=c;$('#status').textContent='Casting…';document.querySelectorAll('.seed').forEach(e=>{e.classList.add('shake');setTimeout(()=>e.classList.remove('shake'),600)});if(sound)tone();setTimeout(()=>{setChain(c);show(c);showReading(c);$('#status').textContent='Consultation complete'},500);save(c)}
function setChain(c){[['left',c.leftBits],['right',c.rightBits]].forEach(([leg,bits])=>document.querySelectorAll(`.seed[data-leg="${leg}"]`).forEach((e,i)=>e.classList.toggle('double',bits[i]==='0')))}function show(c){$('#empty').hidden=true;$('#result').hidden=false;$('#number').textContent=String(c.number).padStart(3,'0');$('#name').textContent=c.name;$('#type').textContent=c.type;const r=marks(c.rightBits),l=marks(c.leftBits);$('#figure').innerHTML=r.map((x,i)=>`<div>${x}&nbsp;&nbsp;&nbsp;${l[i]}</div>`).join('');$('#rightName').textContent=c.right.display;$('#leftName').textContent=c.left.display;$('#rightBits').textContent=c.rightBits;$('#leftBits').textContent=c.leftBits;$('#time').textContent=new Date(c.time).toLocaleString();$('#source').textContent=c.source==='physical'?'Physical Opele entry':'Secure digital cast';const a=c.reading.band;$('#answerClass').className='answerclass '+a.cls;$('#answerClass').textContent=a.label;$('#directAnswer').textContent=a.headline;$('#answerLead').textContent=c.reading.lead}
function showReading(c){const x=c.reading;$('#reading').hidden=false;$('#readingTitle').textContent=c.name+' — '+x.band.label;$('#readingTopic').textContent=TOPICS[x.topic].label;$('#readingQuestion').textContent=c.question;$('#mainMessage').textContent=x.main;$('#rightReadingTitle').textContent=c.right.display;$('#rightReading').textContent=x.right;$('#leftReadingTitle').textContent=c.left.display;$('#leftReading').textContent=x.left;$('#supportTitle').textContent=x.supportTitle;$('#supportText').textContent=x.support;$('#blockTitle').textContent=x.blockTitle;$('#blockText').textContent=x.block;$('#actionTitle').textContent=x.actionTitle;$('#actionText').textContent=x.action;$('#deepReading').textContent=x.deep;const n=$('#safetyNote');if(x.topic==='health'){n.hidden=false;n.textContent='Health note: this divination interpretation cannot diagnose illness or determine whether a treatment is safe. Use it for reflection only and get medical care for symptoms, diagnosis and treatment decisions.'}else if(x.topic==='money'){n.hidden=false;n.textContent='Money note: use this as reflective guidance, not as financial advice or a guarantee of profit, credit, investment returns or contract outcomes.'}else n.hidden=true}
function clear(){current=null;$('#result').hidden=true;$('#empty').hidden=false;$('#reading').hidden=true;$('#status').textContent='Ready for consultation';makeChain()}function history(){try{return JSON.parse(localStorage.getItem('opele-history-v2')||'[]')}catch{return[]}}function save(c){localStorage.setItem('opele-history-v2',JSON.stringify([c,...history()].slice(0,120)));renderHistory()}function revive(c){c.left=B[c.leftBits];c.right=B[c.rightBits];if(!c.reading)c.reading=build(c);current=c;$('#question').value=c.question;manualTopic=c.reading.topic;syncTopic();setChain(c);show(c);showReading(c);$('#status').textContent='Saved consultation';window.scrollTo({top:0,behavior:'smooth'})}
function renderHistory(){const h=history(),box=$('#history');if(!h.length){box.innerHTML='<p style="text-align:center;color:#776a55">No consultations saved yet.</p>';return}box.innerHTML=h.map((c,i)=>`<div class="historyitem" data-i="${i}"><div class="historyfig">${rows(c.rightBits,c.leftBits).replaceAll('\n','<br>')}</div><div><b>${esc(c.name)}</b><p>${esc(c.question)}</p><p class="historyanswer">${esc(c.reading?.band?.label||'Saved cast')}</p></div><time>${new Date(c.time).toLocaleString()}</time></div>`).join('');box.querySelectorAll('.historyitem').forEach(e=>e.onclick=()=>revive(h[+e.dataset.i]))}function renderRefs(){$('#reference').innerHTML='<div class="refs">'+P.map(x=>`<div class="ref"><b>${x.rank}. ${x.display}</b><code>${x.bits}</code><p><strong>${x.core}</strong><br>${x.gift}.<br><em>Caution:</em> ${x.risk}.</p></div>`).join('')+'</div>'}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}function tone(){try{const a=new(window.AudioContext||window.webkitAudioContext),o=a.createOscillator(),g=a.createGain();o.frequency.value=165;g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.15);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.15)}catch{}}
function manual(){const build=(arr,id)=>{const b=$(id);b.innerHTML='';arr.forEach((v,i)=>{const e=document.createElement('button');e.type='button';e.className='mseed';e.textContent=v?'I':'II';e.onclick=()=>{arr[i]=arr[i]?0:1;manual()};b.appendChild(e)})};build(ml,'#mleft');build(mr,'#mright')}function syncTopic(){const t=detectTopic($('#question').value.trim());$('#topicLabel').textContent=TOPICS[t].label;document.querySelectorAll('#topicChips button').forEach(b=>b.classList.toggle('active',b.dataset.topic===t))}
function text(c){const x=c.reading;return`DIGITAL OPELE IFA — CONSULTATION\n\nQuestion: ${c.question}\nTopic: ${TOPICS[x.topic].label}\nOdù: ${c.name}\nType: ${c.type}\nRight: ${c.right.display} (${c.rightBits})\nLeft: ${c.left.display} (${c.leftBits})\n\n${rows(c.rightBits,c.leftBits)}\n\nDIRECT ANSWER\n${x.band.label}\n${x.band.headline}\n\nMAIN MESSAGE\n${x.main}\n\nRIGHT LEG — ${c.right.display}\n${x.right}\n\nLEFT LEG — ${c.left.display}\n${x.left}\n\nWHAT SUPPORTS THE MATTER\n${x.support}\n\nWHAT MAY BLOCK IT\n${x.block}\n\nNEXT STEP\n${x.action}\n\nDEEPER READING\n${x.deep}`}
function loadExpanded(){if(location.protocol!=='file:')return;const s=document.createElement('script');s.src='knowledge.generated.js';s.onload=()=>{if(window.OPELE_EXPANDED){$('#packBadge').textContent='EXPANDED OFFLINE';$('#packInfo').textContent=`Expanded offline interpretation pack ${window.OPELE_EXPANDED.version||''} loaded: ${window.OPELE_EXPANDED.count||'many'} matter-specific variants across all 256 Odù combinations.`;toast('Expanded offline pack loaded')}};document.head.appendChild(s)}
$('#question').addEventListener('input',()=>{manualTopic=null;syncTopic()});document.querySelectorAll('#topicChips button').forEach(b=>b.onclick=()=>{manualTopic=b.dataset.topic;syncTopic()});$('#cast').onclick=()=>{const b=secure();cast(b.slice(0,4).join(''),b.slice(4).join(''))};$('#clear').onclick=clear;$('#manual').onclick=()=>{manual();$('#dialog').showModal()};$('#apply').onclick=e=>{e.preventDefault();$('#dialog').close();cast(ml.join(''),mr.join(''),'physical')};$('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'◉':'○';toast(sound?'Sound on':'Sound off')};$('#copy').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText(text(current));toast('Full consultation copied')}catch{toast('Copy unavailable on this device')}};$('#jumpReading').onclick=()=>$('#reading').scrollIntoView({behavior:'smooth'});$('#sameQuestion').onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#cast').focus(),350)};$('#newQuestion').onclick=()=>{$('#question').value='';manualTopic=null;syncTopic();clear();window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#question').focus(),300)};$('#wipe').onclick=()=>{localStorage.removeItem('opele-history-v2');renderHistory();toast('Consultation history erased')};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tabpane').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')});makeChain();renderHistory();renderRefs();syncTopic();loadExpanded();
